repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-case-conflict

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args: [--disable, MD001, MD004, MD007, MD010, MD012, MD013, MD018, MD022, MD025, MD026, MD031, MD032, MD033, MD034, MD036, MD040, MD041, MD045, --]
        files: _posts/.*\.md$|_pages/.*\.md$
